name: awsug-talent-board

awsug-talent:
  component: "@serverless/website"
  region: ap-southeast-1
  inputs:
    code:
      src: ./build
    # The following two parameters have to be unique for an application. Replace it with your bucket and domain names.
    bucketName: dev-talent-board
    domain: dev-talent-board.awsreskill.com
    env:
      REACT_APP_API_URL: ${env.REACT_APP_API_URL}

